app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['middleware' => 'web'], function () {
    Route::get('/', function () {
        return view('welcome');
    });

    Route::resource('book', 'BooksController');
    Route::resource('collection', 'CollectionsController');
    Route::resource('distributor', 'DistributorsController');
    Route::resource('publisher', 'PublishersController');
    Route::resource('author', 'AuthorsController');
    Route::resource('tag', 'TagsController');
    Route::get('/books-data', ['as' => 'datatables.data', 'uses' => 'BooksController@anyData']);
    Route::post('/books-scraping', ['as' => 'books.scraping', 'uses' => 'BooksController@scraping']);
    Route::get('/books-csv', ['as' => 'books.scrapcsv', 'uses' => 'BooksController@scrapCsv']);
    Route::get('/publisher-collections/{publisher?}', ['as' => 'publisher.collections', 'uses' => 'PublishersController@getCollections']);
});

app/Book.php
<?php 

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'books';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['isbn','collection_id','publisher_id','price','released','title','summary','deposit','buy','distributor_id', 'url_picture'];

    /**
     * Publisher
     */
    public function publisher()
    {
        return $this->belongsTo('App\Publisher');
    }

    /**
     * Distributor
     */
    public function distributor()
    {
        return $this->belongsTo('App\Distributor');
    }

    /**
     * Collection
     */
    public function collection()
    {
        return $this->belongsTo('App\Collection');
    }

    /**
     * Author
     */
    public function authors()
    {
        return $this->belongsToMany('App\Author');
    }

    /**
     * Tags
     */
    public function tags()
    {
        return $this->belongsToMany('App\Tag');
    }
}

app/Http/Controllers/BooksController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Book;
use App\Distributor;
use App\Publisher;
use App\Author;
use App\Tag;
use Illuminate\Http\Request;
use Carbon\Carbon;

use Validator;
use Log;
use Goutte\Client;
use App\DataTables\BooksDataTable;

class BooksController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(BooksDataTable $dataTable)
    {
        $distributors = ['' => 'Choisir un distributeur'] + Distributor::pluck('name', 'id')->all();
        $publishers = ['' => 'Choisir un éditeur'] + Publisher::pluck('name', 'id')->all();
        $authors = Author::pluck('name', 'id')->all();
        $tags = Tag::pluck('name', 'id')->all();
        $collections = array();
        $book = new Book;
        return $dataTable->render('books.index', compact('distributors', 'publishers', 'authors', 'tags', 'collections', 'book'));
    }

    /**
     * Process datatables ajax/actions requests.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function anyData(BooksDataTable $dataTable)
    {
        return $dataTable->render(null);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('books.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $validator = Validator::make($data, [
            'title' => 'required',
            'released' => 'date_format:"d/m/Y"'
        ]);

        if($validator->fails()){
            $this->throwValidationException(
                $request, $validator
            );
        }

        $data = $this->changeFields($data);

        $book = Book::create($data);

        if(isset($data['authors']) && !empty($data['authors']))
        {
            $book->authors()->attach($data['authors']);
        }

        if(isset($data['tags']) && !empty($data['tags']))
        {
            $book->tags()->attach($data['tags']);
        }

        if($request->wantsJson())
        {
            return response()->json($book);
        }

        return redirect('book');
    }

    function changeFields($data)
    {
        if(isset($data['released']) && !empty($data['released']))
        {
            $date = Carbon::createFromFormat('d/m/Y', $data['released']);
            $data['released'] = $date->format('Y-m-d');
        }
        return $data;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show(Request $request, $id)
    {
        $book = Book::findOrFail($id);

        if($request->wantsJson())
        {
            return response()->json($book);
        }

        return view('books.show', compact('book'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $book = Book::findOrFail($id);
        $distributors = ['' => 'Choisir un distributeur'] + Distributor::pluck('name', 'id')->all();
        $publishers = ['' => 'Choisir un éditeur'] + Publisher::pluck('name', 'id')->all();
        $authors = Author::pluck('name', 'id')->all();
        $tags = Tag::pluck('name', 'id')->all();
        $collections = array();
        if($book->released) $book->released = Carbon::parse($book->released)->format('d/m/Y');
        if($book->publisher_id && count($book->publisher->collections) > 0)
        {
            $collections = $book->publisher->collections->pluck('name', 'id')->all();
        }
        return view('books.edit', compact('book', 'distributors', 'publishers', 'authors', 'tags', 'collections'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update($id, Request $request)
    {
        if(!$request->wantsJson())
        {
            $this->validate($request, ['title' => 'required', 'released' => 'date_format:"d/m/Y"']);
        }
        
        $data = $this->changeFields($request->all());

        $book = Book::findOrFail($id);
        $book->update($data);

        if(isset($data['authors']) && !empty($data['authors']))
        {
            $book->authors()->sync($data['authors']);
        }

        if(isset($data['tags']) && !empty($data['tags']))
        {
            $book->tags()->sync($data['tags']);
        }

        if($request->wantsJson())
        {
            return response()->json($book);
        }
        return redirect('book');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        Book::destroy($id);
        return redirect('book');
    }

    public function scrapCsv()
    {
        $csvFile = file_get_contents(storage_path('csv/output.csv'));
        $csvLines = explode("\n", $csvFile);
        foreach ($csvLines as $line) {
            $items = explode("\t", $line);
            $book = null;
            if(count($items) > 0)
            {
                if(!empty($items[1]))
                {
                    $data = $this->scraping(new Request, $items[1]);
                    if($data['book'] != null)
                    {
                        $book = $data['book'];

                        $book->isbn = $items[1];
                        $book->summary = $items[8];
                        if($book->released) $book->released = Carbon::createFromFormat('d/m/Y', $book->released)->format('Y-m-d');

                        $book->save();

                        if(isset($data['authors']) && !empty($data['authors']))
                        {
                            $data['authors'] = array_merge($data['authors']->all(), $data['newAuthors']);
                        }
                        else
                        {
                            $data['authors'] = $data['newAuthors'];
                        }

                        if(isset($data['authors']) && !empty($data['authors']))
                        {
                            $book->authors()->attach(array_pluck($data['authors'], 'id'));
                        }

                        if(!empty($items[0]))
                        {
                            $tags = Tag::where('name', $items[0])->get();
                            if(count($tags) == 0)
                            {
                                $tag = Tag::create(['name' => $items[0]]);
                                $data['newTags'][] = $tag;
                            }
                            else
                            {
                                $data['newTags'][] = $tags[0];
                            }
                        }
                        
                        if(isset($data['tags']) && !empty($data['tags']))
                        {
                            $data['tags'] = array_merge($data['tags']->all(), $data['newTags']);
                        }
                        else
                        {
                            $data['tags'] = $data['newTags'];
                        }

                        if(isset($data['tags']) && !empty($data['tags']))
                        {
                            $book->tags()->attach(array_pluck($data['tags'], 'id'));
                        }
                    }
                }
                if(!isset($book))
                {
                    $book = new Book;
                    $book->isbn = $items[1];
                    $book->title = $items[2];
                    $book->summary = $items[8];
                    if(!empty($items[7]))
                    {
                        $price = str_replace(',', '.', $items[7]);
                        if(is_numeric($price))
                        {
                            $book->price = $price;
                        }
                        
                    }
                    if(!empty($items[4]))
                    {
                        $editeur = Publisher::where(['name' => $items[4]])->first();
                        if ($editeur != null)
                        {
                            $book->publisher_id = $editeur->id;
                        }
                        else
                        {
                            $newPublisher = Publisher::create(['name' => $items[4]]);
                            $book->publisher_id = $newPublisher->id;
                        }
                    }
                    
                    $book->save();

                    if(!empty($items[3]))
                    {
                        $authors = Author::where('name', $items[3])->get();
                        if(count($authors) == 0)
                        {
                            $author = Author::create(['name' => $items[3]]);
                            $book->authors()->attach($author->id);
                        }
                        elseif (count($authors) >= 1)
                        {
                            $book->authors()->attach($authors[0]->id);
                        }
                    }

                    if(!empty($items[0]))
                    {
                        $tags = Tag::where('name', $items[0])->get();
                        if(count($tags) == 0)
                        {
                            $tag = Tag::create(['name' => $items[0]]);
                            $book->tags()->attach($tag->id);
                        }
                        else
                        {
                            $book->tags()->attach($tags[0]->id);
                        }
                    }
                }

resources/views/books/_authors.blade.php
<div id="pop-author-form" class="white-popup mfp-hide">
    <div class="panel panel-default">
        <div class="panel-heading">Nouvel-le auteur-e</div>
        <div class="panel-body">
            {!! Form::open(['url' => 'author', 'class' => 'form-horizontal', 'id' => 'newAuthor']) !!}
                <div class="col-xs-12">
                    <div class="form-group">
                        {!! Form::label('name', 'Nom: ', ['class' => 'col-sm-3 control-label']) !!}
                        <div class="col-sm-9">
                            {!! Form::text('name', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-3">
                            {!! Form::submit('Créer', ['class' => 'btn btn-primary form-control']) !!}
                        </div>    
                    </div>
                </div>
            {!! Form::close() !!}
        </div>
        
    </div>
</div>

resources/views/books/_collections.blade.php
<div id="pop-collection-form" class="white-popup mfp-hide">
    <div class="panel panel-default">
        <div class="panel-heading">Nouvelle collection</div>
        <div class="panel-body">
            {!! Form::open(['url' => 'collection', 'class' => 'form-horizontal', 'id' => 'newCollection']) !!}
                <input type="hidden" name="publisher_id" id="collection_publisher" value="0">
                <div class="col-xs-12">
                    <div class="form-group">
                        {!! Form::label('name', 'Nom: ', ['class' => 'col-sm-3 control-label']) !!}
                        <div class="col-sm-9">
                            {!! Form::text('name', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-3">
                            {!! Form::submit('Créer', ['class' => 'btn btn-primary form-control']) !!}
                        </div>    
                    </div>
                </div>
            {!! Form::close() !!}
        </div>
        
    </div>
</div>

resources/views/books/_distributors.blade.php
<div id="pop-distributor-form" class="white-popup mfp-hide">
    <div class="panel panel-default">
        <div class="panel-heading">Nouveau distributeur</div>
        <div class="panel-body">
            {!! Form::open(['url' => 'distributor', 'class' => 'form-horizontal', 'id' => 'newDistributor']) !!}
                <div class="col-xs-12">
                    <div class="form-group">
                        {!! Form::label('name', 'Nom: ', ['class' => 'col-sm-3 control-label']) !!}
                        <div class="col-sm-9">
                            {!! Form::text('name', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        {!! Form::label('phone', 'Tel: ', ['class' => 'col-sm-3 control-label']) !!}
                        <div class="col-sm-9">
                            {!! Form::text('phone', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        {!! Form::label('mail', 'Email: ', ['class' => 'col-sm-3 control-label']) !!}
                        <div class="col-sm-9">
                            {!! Form::text('mail', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        {!! Form::label('address', 'Adresse: ', ['class' => 'col-sm-3 control-label']) !!}
                        <div class="col-sm-9">
                            {!! Form::text('address', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        {!! Form::label('city', 'Ville: ', ['class' => 'col-sm-3 control-label']) !!}
                        <div class="col-sm-9">
                            {!! Form::text('city', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        {!! Form::label('zip', 'Code Postal: ', ['class' => 'col-sm-3 control-label']) !!}
                        <div class="col-sm-9">
                            {!! Form::text('zip', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-3">
                            {!! Form::submit('Créer', ['class' => 'btn btn-primary form-control']) !!}
                        </div>    
                    </div>
                </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>

resources/views/books/_form.blade.php
<input type="hidden" id="url-scraping" value="{{ route('books.scraping') }}">
<input type="hidden" id="url-collections" value="{{ route('publisher.collections') }}">
<input type="hidden" id="book-show" value="{{ route('book.show', ['id' => 0]) }}">

@if(!isset($book->id))
    {!! Form::model($book, ['route' => 'book.store', 'class' => 'form-horizontal', 'id' => 'newBook']) !!}
@else
    {!! Form::model($book, ['route' => ['book.update', $book->id], 'method' => 'put', 'class' => 'form-horizontal', 'id' => 'editBook']) !!}
@endif

    <hr>
    <div class="col-lg-6">
        <div class="form-group">
            {!! Form::label('isbn', 'ISBN: ', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-9">
                {!! Form::number('isbn', $book->isbn, ['class' => 'form-control']) !!}
            </div>
        </div>
        <div class="form-group">
            {!! Form::label('title', 'Titre: ', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-9">
                {!! Form::text('title', $book->title, ['class' => 'form-control']) !!}
                <small class="help-block"></small>
            </div>
        </div>
        <div class="form-group">
            {!! Form::label('publisher_id', 'Éditeur : ', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-9">
                <div class="input-group">
                    {!! Form::select('publisher_id', $publishers, $book->publisher_id, ['class' => 'form-control']) !!}
                    <a class="input-group-addon new-publisher open-popup-link" href="#pop-publisher-form">+</a>
                </div>
            </div>
        </div>
        <div class="form-group collection" style="@if($book->publisher_id == null) display:none @endif">
            {!! Form::label('collection_id', 'Collection: ', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-9">
                <div class="input-group">
                    {!! Form::select('collection_id', $collections, $book->collection_id, ['class' => 'form-control']) !!}
                    <a class="input-group-addon new-collection open-popup-link" href="#pop-collection-form">+</a>
                </div>
            </div>
        </div>
        <div class="form-group">
            {!! Form::label('authors', 'Auteurs: ', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-9">
                <div class="input-group">
                    {!! Form::select('authors', $authors, $book->authors->pluck('id')->all(), ['class' => 'form-control', 'multiple' => 'multiple', 'name'=>'authors[]']) !!}
                    <a class="input-group-addon new-author open-popup-link" href="#pop-author-form">+</a>
                </div>
            </div>
        </div>
        <div class="form-group">
            {!! Form::label('price', 'Prix: ', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-9">
                {!! Form::number('price', $book->price, ['class' => 'form-control', 'step' => 'any', 'min' => '0']) !!}
            </div>
        </div>
        <div class="form-group">
            {!! Form::label('released', 'Publié le: ', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-9">
                {!! Form::date('released', $book->released, ['class' => 'form-control']) !!}
                <small class="help-block"></small>
            </div>
        </div>
        <div class="form-group">
            {!! Form::label('deposit', 'Dépôts: ', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-9">
                {!! Form::number('deposit', $book->deposit, ['class' => 'form-control']) !!}
            </div>
        </div>
        <div class="form-group">
            {!! Form::label('buy', 'Achats fermes: ', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-9">
                {!! Form::number('buy', $book->buy, ['class' => 'form-control']) !!}
            </div>
        </div>
        <div class="form-group">
            {!! Form::label('distributor_id', 'Distributeur: ', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-9">
                <div class="input-group">
                    {!! Form::select('distributor_id', $distributors, $book->distributors, ['class' => 'form-control']) !!}
                    <a class="input-group-addon new-distributor open-popup-link" href="#pop-distributor-form">+</a>
                </div>
            </div>
        </div>
        <div class="form-group">
            {!! Form::label('tags', 'Tags: ', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-9">
                <div class="input-group">
                    {!! Form::select('tags', $tags, $book->tags->pluck('id')->all(), ['class' => 'form-control', 'multiple' => 'multiple', 'name'=>'tags[]']) !!}
                    <a class="input-group-addon new-tag open-popup-link" href="#pop-tag-form">+</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="form-group">
            {!! Form::label('url_picture', 'URL image: ', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-9">
                {!! Form::text('url_picture', $book->url_picture, ['class' => 'form-control']) !!}
                <img id="picture" src="{{ $book->url_picture or '#' }}" alt="">
            </div>
        </div>
        <div class="form-group">
            {!! Form::label('summary', 'Résumé: ', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-9">
                {!! Form::textarea('summary', $book->summary, ['class' => 'form-control', 'rows' => 5]) !!}
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                @if(!isset($book->id))
                    {!! Form::submit('Créer', ['class' => 'btn btn-primary form-control']) !!}
                @else
                    {!! Form::submit('Appliquer les modifications', ['class' => 'btn btn-primary form-control']) !!}
                @endif
            </div>    
        </div>
    </div>
{!! Form::close() !!}

resources/views/books/_publishers.blade.php
<div id="pop-publisher-form" class="white-popup mfp-hide">
    <div class="panel panel-default">
        <div class="panel-heading">Nouvel éditeur</div>
        <div class="panel-body">
            {!! Form::open(['url' => 'publisher', 'class' => 'form-horizontal', 'id' => 'newPublisher']) !!}
                <div class="col-xs-12">
                    <div class="form-group">
                        {!! Form::label('name', 'Nom: ', ['class' => 'col-sm-3 control-label']) !!}
                        <div class="col-sm-9">
                            {!! Form::text('name', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        {!! Form::label('phone', 'Tel: ', ['class' => 'col-sm-3 control-label']) !!}
                        <div class="col-sm-9">
                            {!! Form::text('phone', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        {!! Form::label('mail', 'Email: ', ['class' => 'col-sm-3 control-label']) !!}
                        <div class="col-sm-9">
                            {!! Form::text('mail', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        {!! Form::label('address', 'Adresse: ', ['class' => 'col-sm-3 control-label']) !!}
                        <div class="col-sm-9">
                            {!! Form::text('address', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        {!! Form::label('city', 'Ville: ', ['class' => 'col-sm-3 control-label']) !!}
                        <div class="col-sm-9">
                            {!! Form::text('city', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        {!! Form::label('zip', 'Code Postal: ', ['class' => 'col-sm-3 control-label']) !!}
                        <div class="col-sm-9">
                            {!! Form::text('zip', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-3">
                            {!! Form::submit('Créer', ['class' => 'btn btn-primary form-control']) !!}
                        </div>    
                    </div>
                </div>
            {!! Form::close() !!}
        </div>
        
    </div>
</div>

resources/views/books/_tags.blade.php
<div id="pop-tag-form" class="white-popup mfp-hide">
    <div class="panel panel-default">
        <div class="panel-heading">Nouveau tag</div>
        <div class="panel-body">
            {!! Form::open(['url' => 'tag', 'class' => 'form-horizontal', 'id' => 'newTag']) !!}
                <div class="col-xs-12">
                    <div class="form-group">
                        {!! Form::label('name', 'Nom: ', ['class' => 'col-sm-3 control-label']) !!}
                        <div class="col-sm-9">
                            {!! Form::text('name', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-3">
                            {!! Form::submit('Créer', ['class' => 'btn btn-primary form-control']) !!}
                        </div>    
                    </div>
                </div>
            {!! Form::close() !!}
        </div>
        
    </div>
</div>

resources/views/books/index.blade.php
@extends('layouts.master')

@section('content')
    <button onclick="$('#newBook').show();$(this).hide();$('#hideForm').show();" id="showNewForm" class="btn btn-primary">Ajouter une entrée</button>
    <button onclick="$('#newBook').hide();$('#showNewForm').show();$(this).hide();" class="btn btn-warning" id="hideForm" style="display: none">Masquer le formulaire</button>
    
    <div class="alert alert-success alert-dismissible hidden" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>Ouvrage correctement ajouté.</strong>
    </div> 

    @include('books._form')
    @include('books._tags')
    @include('books._distributors')
    @include('books._publishers')
    @include('books._collections')
    @include('books._authors')

    <div class="row">
        <div class="col-xs-12">
            <hr>
            {!! $dataTable->table(['id' => 'books-table', 'class' => 'table table-striped']) !!}
        </div>
    </div>
    
    <div id="pop-book-form" class="white-popup mfp-hide">
        <div class="panel panel-default">
            <div class="panel-heading">Modification rapide</div>
            <div class="panel-body">
                {!! Form::open(['route' => ['book.update', 0], 'method' => 'put', 'class' => 'form-horizontal', 'id' => 'editBook']) !!}
                    <div class="col-xs-12">
                        <div class="form-group">
                            {!! Form::label('buy', 'Quantité achats fermes: ', ['class' => 'col-sm-3 control-label']) !!}
                            <div class="col-sm-9">
                                {!! Form::number('buy', null, ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="form-group">
                            {!! Form::label('deposit', 'Quantité dépôts: ', ['class' => 'col-sm-3 control-label']) !!}
                            <div class="col-sm-9">
                                {!! Form::number('deposit', null, ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-9">
                                <a href="{{ route('book.edit', ['id' => 0]) }}">Modifications avancées</a>
                            </div>    
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-9">
                                {!! Form::submit('Enregistrer', ['class' => 'btn btn-primary form-control']) !!}
                            </div>    
                        </div>
                    </div>
                {!! Form::close() !!}
            </div>
            
        </div>
    </div>

@endsection

@push('scripts')
    <script src="{{ asset('js/jquery.form.min.js') }}"></script>
    <script src="{{ asset('js/books.js') }}"></script>
    {!! $dataTable->scripts() !!}
    <script>
        $(function() {
            
            $('#newBook').ajaxForm({success: addBook, error: showErrors, dataType: 'json', resetForm: true});
            $('#newPublisher').ajaxForm({success: addAndHidePublisherForm, dataType: 'json', resetForm: true});
            $('#newCollection').ajaxForm({success: addAndHideCollectionForm, dataType: 'json', resetForm: true});
            $('#newDistributor').ajaxForm({success: addAndHideDistributorForm, dataType: 'json', resetForm: true});
            $('#newAuthor').ajaxForm({success: addAndHideAuthorForm, dataType: 'json', resetForm: true});
            $('#newTag').ajaxForm({success: addAndHideTagForm, dataType: 'json', resetForm: true});
            $('#editBook').ajaxForm({success: hideBookForm, dataType: 'json', resetForm: true});
        });
    </script>
@endpush